### ISSUE TITLE
java.lang.Object  crash

### ISSUE THREAD

**Issue by louiewh** [tinylcy/ClassAnalyzer#3]
cpInfo[76] = ConstantUtf8Info{bytesValue='(I)Ljava/lang/String;'}
cpInfo[77] = ConstantUtf8Info{bytesValue='(Ljava/lang/String;)V'}
accessFlags = 21, public super 
thisClass = 17, this class name = java/lang/Object
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.wh.jvm.classfile.ClassReader.getConstantClassInfoValue(ClassReader.java:200)
	at com.wh.jvm.classfile.ClassReader.analyze(ClassReader.java:36)
	at com.wh.jvm.Main.main(Main.java:33)

java.lang.Object   superClass.getValue is 0 ,  so getConstantClassInfoValue happen Exception

**Comment by tinylcy** [comment]
Hi @louiewh ,

I have fixed the error and thanks you for taking time to report this bug.
